from enum import Enum


class ParsingState(Enum):
    EXPECTING_HTTP_METHOD = 0
    EXPECTING_FILE_NAME = 1
    EXPECTING_HOST_NAME = 2
    EXPECTING_OPTIONAL_PORT_NUMBER = 3
    EXPECTING_OPTIONAL_HEADERS = 4
    EXPECTING_OPTIONAL_PAYLOAD = 5
